name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkout-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r src/requirements.txt

      # Step 4: Run tests
      - name: Run unit tests
        run: |
          pytest

  trivyfs:
    #  needs: checkout-test
    runs-on: ubuntu-latest

    steps:
      - name: Install trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: run the filesystem scan
        run: |
          trivy fs --scanners vuln --format table src/
