name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dockerbuild:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.0"

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run the Flask application
      - name: Run Flask app
        run: python app.py

      - name: Run tests
        run: pytest src/test/
